---
resources:
- name: cd-enablement
  type: git
  source:
    uri: https://github.com/pivotal-cf/cd-enablement.git
    branch: master
- name: spring-music
  type: git
  source:
    uri: https://github.com/cloudfoundry-samples/spring-music.git
    branch: master

jobs:
- name: scan
  plan:
  - aggregate:
    - get: cd-enablement
    - get: spring-music
  - task: blackduck
    file: cd-enablement/tasks/blackduck/blackduck.yml
    input_mapping:
      repo: spring-music
    params:
      HUB_URL: ((hub_url))
      HUB_USERNAME: ((hub_username))
      HUB_PASSWORD: ((hub_password))
